%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'rbc';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('rbc.log');
M_.exo_names = 'epsA';
M_.exo_names_tex = 'epsA';
M_.exo_names_long = 'epsA';
M_.exo_names = char(M_.exo_names, 'eps_psi');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_psi');
M_.exo_names_long = char(M_.exo_names_long, 'eps_psi');
M_.endo_names = 'k';
M_.endo_names_tex = 'k';
M_.endo_names_long = 'k';
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'logit_delta');
M_.endo_names_tex = char(M_.endo_names_tex, 'logit\_delta');
M_.endo_names_long = char(M_.endo_names_long, 'logit_delta');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi');
M_.endo_names_long = char(M_.endo_names_long, 'pi');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names_long = char(M_.endo_names_long, 'mc');
M_.endo_names = char(M_.endo_names, 'disp');
M_.endo_names_tex = char(M_.endo_names_tex, 'disp');
M_.endo_names_long = char(M_.endo_names_long, 'disp');
M_.endo_names = char(M_.endo_names, 'psi');
M_.endo_names_tex = char(M_.endo_names_tex, 'psi');
M_.endo_names_long = char(M_.endo_names_long, 'psi');
M_.endo_names = char(M_.endo_names, 'spread');
M_.endo_names_tex = char(M_.endo_names_tex, 'spread');
M_.endo_names_long = char(M_.endo_names_long, 'spread');
M_.endo_names = char(M_.endo_names, 'inv');
M_.endo_names_tex = char(M_.endo_names_tex, 'inv');
M_.endo_names_long = char(M_.endo_names_long, 'inv');
M_.endo_names = char(M_.endo_names, 'Y');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y');
M_.endo_names_long = char(M_.endo_names_long, 'Y');
M_.endo_names = char(M_.endo_names, 'H');
M_.endo_names_tex = char(M_.endo_names_tex, 'H');
M_.endo_names_long = char(M_.endo_names_long, 'H');
M_.param_names = 'varrho';
M_.param_names_tex = 'varrho';
M_.param_names_long = 'varrho';
M_.param_names = char(M_.param_names, 'alp');
M_.param_names_tex = char(M_.param_names_tex, 'alp');
M_.param_names_long = char(M_.param_names_long, 'alp');
M_.param_names = char(M_.param_names, 'zzeta');
M_.param_names_tex = char(M_.param_names_tex, 'zzeta');
M_.param_names_long = char(M_.param_names_long, 'zzeta');
M_.param_names = char(M_.param_names, 'betta');
M_.param_names_tex = char(M_.param_names_tex, 'betta');
M_.param_names_long = char(M_.param_names_long, 'betta');
M_.param_names = char(M_.param_names, 'deltaSS');
M_.param_names_tex = char(M_.param_names_tex, 'deltaSS');
M_.param_names_long = char(M_.param_names_long, 'deltaSS');
M_.param_names = char(M_.param_names, 'sigma_c');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_c');
M_.param_names_long = char(M_.param_names_long, 'sigma_c');
M_.param_names = char(M_.param_names, 'rhodelta');
M_.param_names_tex = char(M_.param_names_tex, 'rhodelta');
M_.param_names_long = char(M_.param_names_long, 'rhodelta');
M_.param_names = char(M_.param_names, 'rhoA');
M_.param_names_tex = char(M_.param_names_tex, 'rhoA');
M_.param_names_long = char(M_.param_names_long, 'rhoA');
M_.param_names = char(M_.param_names, 'rho_psi');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_psi');
M_.param_names_long = char(M_.param_names_long, 'rho_psi');
M_.param_names = char(M_.param_names, 'Ass');
M_.param_names_tex = char(M_.param_names_tex, 'Ass');
M_.param_names_long = char(M_.param_names_long, 'Ass');
M_.param_names = char(M_.param_names, 'Phi');
M_.param_names_tex = char(M_.param_names_tex, 'Phi');
M_.param_names_long = char(M_.param_names_long, 'Phi');
M_.param_names = char(M_.param_names, 'sigmaB');
M_.param_names_tex = char(M_.param_names_tex, 'sigmaB');
M_.param_names_long = char(M_.param_names_long, 'sigmaB');
M_.param_names = char(M_.param_names, 'xiB');
M_.param_names_tex = char(M_.param_names_tex, 'xiB');
M_.param_names_long = char(M_.param_names_long, 'xiB');
M_.param_names = char(M_.param_names, 'Theta');
M_.param_names_tex = char(M_.param_names_tex, 'Theta');
M_.param_names_long = char(M_.param_names_long, 'Theta');
M_.param_names = char(M_.param_names, 'kappaSS');
M_.param_names_tex = char(M_.param_names_tex, 'kappaSS');
M_.param_names_long = char(M_.param_names_long, 'kappaSS');
M_.param_names = char(M_.param_names, 'logit_deltaSS');
M_.param_names_tex = char(M_.param_names_tex, 'logit\_deltaSS');
M_.param_names_long = char(M_.param_names_long, 'logit_deltaSS');
M_.param_names = char(M_.param_names, 'epsilon');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon');
M_.param_names_long = char(M_.param_names_long, 'epsilon');
M_.param_names = char(M_.param_names, 'kappa_GK');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_GK');
M_.param_names_long = char(M_.param_names_long, 'kappa_GK');
M_.param_names = char(M_.param_names, 'gam');
M_.param_names_tex = char(M_.param_names_tex, 'gam');
M_.param_names_long = char(M_.param_names_long, 'gam');
M_.param_names = char(M_.param_names, 'sigma_a');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_a');
M_.param_names_long = char(M_.param_names_long, 'sigma_a');
M_.param_names = char(M_.param_names, 'sigma_psi');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_psi');
M_.param_names_long = char(M_.param_names_long, 'sigma_psi');
M_.param_names = char(M_.param_names, 'sigma_delta');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_delta');
M_.param_names_long = char(M_.param_names_long, 'sigma_delta');
M_.param_names = char(M_.param_names, 'deltabar');
M_.param_names_tex = char(M_.param_names_tex, 'deltabar');
M_.param_names_long = char(M_.param_names_long, 'deltabar');
M_.param_names = char(M_.param_names, 'logit_deltabar');
M_.param_names_tex = char(M_.param_names_tex, 'logit\_deltabar');
M_.param_names_long = char(M_.param_names_long, 'logit_deltabar');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'sigma_h');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_h');
M_.param_names_long = char(M_.param_names_long, 'sigma_h');
M_.param_names = char(M_.param_names, 'psi_h');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_h');
M_.param_names_long = char(M_.param_names_long, 'psi_h');
M_.param_names = char(M_.param_names, 'epsilonC');
M_.param_names_tex = char(M_.param_names_tex, 'epsilonC');
M_.param_names_long = char(M_.param_names_long, 'epsilonC');
M_.param_names = char(M_.param_names, 'epsilonH');
M_.param_names_tex = char(M_.param_names_tex, 'epsilonH');
M_.param_names_long = char(M_.param_names_long, 'epsilonH');
M_.param_names = char(M_.param_names, 'gam_jr');
M_.param_names_tex = char(M_.param_names_tex, 'gam\_jr');
M_.param_names_long = char(M_.param_names_long, 'gam_jr');
M_.param_names = char(M_.param_names, 'theta_jr');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_jr');
M_.param_names_long = char(M_.param_names_long, 'theta_jr');
M_.param_names = char(M_.param_names, 'C_bar');
M_.param_names_tex = char(M_.param_names_tex, 'C\_bar');
M_.param_names_long = char(M_.param_names_long, 'C_bar');
M_.param_names = char(M_.param_names, 'H_bar');
M_.param_names_tex = char(M_.param_names_tex, 'H\_bar');
M_.param_names_long = char(M_.param_names_long, 'H_bar');
M_.param_names = char(M_.param_names, 'GSS');
M_.param_names_tex = char(M_.param_names_tex, 'GSS');
M_.param_names_long = char(M_.param_names_long, 'GSS');
M_.exo_det_nbr = 0;
M_.exo_nbr = 2;
M_.endo_nbr = 14;
M_.param_nbr = 34;
M_.orig_endo_nbr = 14;
M_.aux_vars = [];
M_.Sigma_e = zeros(2, 2);
M_.Correlation_matrix = eye(2, 2);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('rbc_static');
erase_compiled_function('rbc_dynamic');
M_.lead_lag_incidence = [
 1 7 0;
 2 8 0;
 0 9 21;
 0 10 22;
 3 11 23;
 0 12 0;
 0 13 24;
 0 14 25;
 0 15 26;
 4 16 27;
 0 17 0;
 5 18 28;
 0 19 0;
 6 20 29;]';
M_.nstatic = 3;
M_.nfwrd   = 5;
M_.npred   = 2;
M_.nboth   = 4;
M_.nsfwrd   = 9;
M_.nspred   = 6;
M_.ndynamic   = 11;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:2];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(14, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(2, 1);
M_.params = NaN(34, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 82;
M_.NNZDerivatives(2) = 551;
M_.NNZDerivatives(3) = -1;
load('../opts.mat');
M_.params( 1 ) = 0.684;
varrho = M_.params( 1 );
M_.params( 2 ) = 0.3;
alp = M_.params( 2 );
M_.params( 3 ) = 7.0;
zzeta = M_.params( 3 );
M_.params( 4 ) = 0.995;
betta = M_.params( 4 );
M_.params( 23 ) = 0.025;
deltabar = M_.params( 23 );
M_.params( 24 ) = log(M_.params(23)/(1-M_.params(23)));
logit_deltabar = M_.params( 24 );
M_.params( 6 ) = parameter_sigma_c;
sigma_c = M_.params( 6 );
M_.params( 30 ) = parameter_gam_jr;
gam_jr = M_.params( 30 );
M_.params( 31 ) = parameter_theta_jr;
theta_jr = M_.params( 31 );
M_.params( 26 ) = parameter_sigma_h;
sigma_h = M_.params( 26 );
M_.params( 27 ) = parameter_psi_h;
psi_h = M_.params( 27 );
M_.params( 25 ) = .7;
chi = M_.params( 25 );
M_.params( 28 ) = parameter_habits_C;
epsilonC = M_.params( 28 );
M_.params( 29 ) = parameter_habits_H;
epsilonH = M_.params( 29 );
M_.params( 10 ) = 1;
Ass = M_.params( 10 );
M_.params( 8 ) = parameter_rhoA;
rhoA = M_.params( 8 );
M_.params( 7 ) = parameter_rhodelta;
rhodelta = M_.params( 7 );
M_.params( 9 ) = parameter_rho_psi;
rho_psi = M_.params( 9 );
M_.params( 12 ) = 0.975;
sigmaB = M_.params( 12 );
M_.params( 13 ) = 0.00017;
xiB = M_.params( 13 );
M_.params( 17 ) = (-2);
epsilon = M_.params( 17 );
M_.params( 18 ) = 13;
kappa_GK = M_.params( 18 );
M_.params( 19 ) = 1e-8;
gam = M_.params( 19 );
M_.params( 15 ) = parameter_kappa;
kappaSS = M_.params( 15 );
M_.params( 14 ) = parameter_Theta;
Theta = M_.params( 14 );
M_.params( 11 ) = parameter_Phi;
Phi = M_.params( 11 );
M_.params( 20 ) = parameter_sigma_a;
sigma_a = M_.params( 20 );
M_.params( 21 ) = parameter_sigma_psi;
sigma_psi = M_.params( 21 );
M_.params( 22 ) = parameter_sigma_delta;
sigma_delta = M_.params( 22 );
M_.params( 16 ) = M_.params(24);
logit_deltaSS = M_.params( 16 );
M_.params( 5 ) = 1/(1+exp((-M_.params(16))));
deltaSS = M_.params( 5 );
M_.params( 33 ) = 1/(1+M_.params(1)/(1-M_.params(1))*(1-M_.params(28))/(1-M_.params(29))*(1-gySS-M_.params(5)*M_.params(2)/(1/M_.params(4)-(1-M_.params(5))))/(1-M_.params(2)));
H_bar = M_.params( 33 );
M_.params( 32 ) = (1-gySS-M_.params(5)*M_.params(2)/(1/M_.params(4)-(1-M_.params(5))))*M_.params(10)*M_.params(33)*(M_.params(2)/(1/M_.params(4)-(1-M_.params(5))))^(M_.params(2)/(1-M_.params(2)));
C_bar = M_.params( 32 );
steady;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 1;
M_.Sigma_e(2, 2) = 1;
options_.irf = 0;
options_.order = 2;
options_.periods = 1000;
var_list_=[];
info = stoch_simul(var_list_);
save('rbc_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('rbc_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('rbc_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('rbc_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('rbc_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
